# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 879d38a6f548272599baf1c4a10b228f276705e30508d4b37522fff6a2857c0b1f46f7b66a84537cf7f2bd7d74ff747658b32b11ca9bcc0bf1ae143c540eb76f

test:
  secret_key_base: 5f20eb4959f87c3fed06d2b2ddeab1532f45e4368e3d6b3b194ad6c123c69e0c85b86ee557ad900e83affa9b607f2f9cda78193be8af907d433066e54207ea70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
